agent:
  model:
    name: gpt-5.4
    temperature: 1.0
    top_p: null
    api_base: https://api.tabcode.cc/openai
    api_key: $OPENAI_API_KEY
    litellm_model_registry: /data/liora/SWE-agent-src/config/litellm_model_registry_gpt54.json
